services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env  # ✅ Load AWS RDS credentials from .env
    ports:
      - "8000:8000"
    depends_on:
      - nginx  # ✅ Flask should only depend on Nginx now
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # ✅ Correct Nginx config path
    depends_on:
      - flask_app  # ✅ Nginx should wait for Flask
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
