services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    env_file:
      - .env  # ✅ Load AWS RDS credentials
    ports:
      - "8000:8000"
    networks:
      - app_network  # ✅ No longer depends on Nginx
    network_mode: "host"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # ✅ Correct config path
    depends_on:
      - flask_app  # ✅ Only Nginx depends on Flask
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
