"""Initial migration

Revision ID: c59a87126951
Revises: 8fc0cda52814
Create Date: 2025-02-14 23:15:31.495859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c59a87126951'
down_revision = '8fc0cda52814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
