"""Added voucher_status to Order model

Revision ID: de253900b1ba
Revises: c59a87126951
Create Date: 2025-02-17 18:09:56.795183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de253900b1ba'
down_revision = 'c59a87126951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_status', sa.Enum('unused', 'used'), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('image_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('voucher_status')

    # ### end Alembic commands ###
